#pragma once

#define MATRIX_MULTIPLICATION_VERSION "1.0"

#define MATRIX_MULTIPLICATION_VERSION_MAJOR 1
#define MATRIX_MULTIPLICATION_VERSION_MINOR 0
#define MATRIX_MULTIPLICATION_VERSION_PATCH 0
#define MATRIX_MULTIPLICATION_VERSION_TWEAK 0
