name: Ubuntu

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  #CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          #path: "**/cpm_modules"
          path: cpm_modules
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}


      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

      - name: Configure
        run: |
          cmake -S ./test -B ./build/test -G "Ninja" \
          -DCMAKE_INSTALL_PREFIX=./install \
          -DCMAKE_BUILD_TYPE=Release

        #cmake -Stest -Bbuild -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build ./build/test --parallel 4

      - name: test
        run: |
          ctest --test-dir ./build/test --output-on-failure

      #- name: collect code coverage
        #run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"



